enum HTTP_METHODS {
    GET = "GET",
    POST = "POST",
    PUT = "PUT",
    DELETE = "DELETE",
    PATCH = "PATCH",
    OPTIONS = "OPTIONS",
    HEAD = "HEAD"
}

const METHODS_WITH_BODY = new Set([
    HTTP_METHODS.POST,
    HTTP_METHODS.PUT,
    HTTP_METHODS.PATCH,
    HTTP_METHODS.DELETE
]);

const METHODS_WITHOUT_BODY = new Set([
    HTTP_METHODS.GET,
    HTTP_METHODS.HEAD,
    HTTP_METHODS.OPTIONS
]);



export { HTTP_METHODS, METHODS_WITH_BODY, METHODS_WITHOUT_BODY };